"""order_item_product_nullable

Revision ID: 258e6008cc86
Revises: 51c398528256
Create Date: 2026-03-07 13:46:02.530541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258e6008cc86'
down_revision = '51c398528256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
