"""add case_material_en movement_en to product

Revision ID: 38e31187c362
Revises: 4067fac30805
Create Date: 2026-04-12 18:48:59.265564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e31187c362'
down_revision = '4067fac30805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_material_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('movement_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('water_resistance_en', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('water_resistance_en')
        batch_op.drop_column('movement_en')
        batch_op.drop_column('case_material_en')

    # ### end Alembic commands ###
